# This is all the wiki related stuff
## Wikipedia
WIKIPEDIA_BZ2_URL=http://download.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

## Wikipedia Dump unzipped
# This is not really to be used just have it here in case anyone wants
# to look at
wikipedia-dump.xml-bz-url=$(WIKIPEDIA_BZ2_URL)
BZ_PROJECTS += wikipedia-dump.xml

wikipedia-dump-xml: wikipedia-dump.xml

wikipedia-dump-xml-clean: wikipedia-dump.xml-bz-clean

## Wikipedia Dump raw
# mwdumper handles bziped archives so we just need this raw. Look
# above if you need plain xml.

wikipedia-dump.xml.bz2-raw-url=$(WIKIPEDIA_BZ2_URL)
RAW_PROJECTS += wikipedia-dump.xml.bz2

wikipedia-dump : wikipedia-dump.xml.bz2
	@echo "Getting the raw dump."

## MWDumper
# You will need jde and jre. For more info see here:
# http://www.mediawiki.org/wiki/Mwdumper
mwdumper-git-repo=https://git.wikimedia.org/git/mediawiki/tools/mwdumper.git
GIT_PROJECTS += mwdumper
MWDUMPER_JAR_BUILT=$(SOURCES_DIR)/mwdumper-git/target/mwdumper-1.16.jar

$(TOOLS_DIR)/mwdumper.jar: mwdumper | $(TOOLS_DIR)
	cd $(SOURCES_DIR)/mwdumper-git/ && \
	mvn package
	cp $(SOURCES_DIR)/mwdumper-git/target/mwdumper-1.16.jar $(TOOLS_DIR)/mwdumper.jar

$(DRAFTS_DIR)/wikipedia_dump.sql: wikipedia-dump bitnami-mediawiki-build $(TOOLS_DIR)/mwdumper.jar
	java -jar $(TOOLS_DIR)/mwdumper.jar --format=sql:1.5 $(DRAFTS_DIR)/raw-wikipedia-dump.xml.bz2 > $(DRAFTS_DIR)/wikipedia_dump.sql

# XXX: move this to the server stack
mwdumper-load: $(DRAFTS_DIR)/wikipedia_dump.sql
	$(FILESYSTEM_ROOT)/mysql/bin/mysql -u $(MYSQL_USER) -p $(MYSQL_PASS)


###### WikiMedia vanilla build. ######
# Below is a wikimedia build that applies if you use a server stack
# that does not contain wikimedia.

HTDOCS_DIR=/opt/lampp/htdocs
HTDOCS_SUBDIR=wikipedia
WIKIMEDIA_ROOT=$(HTDOCS_DIR)/$(HTDOCS_SUBDIR)
WIKI_ROOTACCESS=fakeroot

## DOC
# This will try to set recursive perimission to htdocs directory with
# HTDOCS_PERMISSIONS which defaults to a+rw. Use symbolic or numerical.
HTDOCS_PERMISSIONS=a+rw

DIRECTORIES += $(WIKIMEDIA_ROOT)

## DOC
# Dependency: rsync
SYNC=rsync -zvr

.PHONY: htdocs-permissions
htdocs-permissions:
	$(ROOTACCESS) chmod -R $(HTDOCS_PERMISSIONS) $(HTDOCS_DIR)

wikimedia-tar-url=http://download.wikimedia.org/mediawiki/1.21/mediawiki-1.21.3.tar.gz
TAR_PROJECTS += wikimedia
wikimedia-build: wikimedia htdocs-permissions | $(WIKIMEDIA_ROOT)
	cd $(SOURCES_DIR)/wikimedia-archive/ ; \
	$(SYNC) $(SOURCES_DIR)/wikimedia-archive/*/ $(WIKIMEDIA_ROOT)

# Purposely avoided htdocs-permissions as a dependency. If we had
# created it we would be able to remove it.
wikimedia-uninstall:
	rm -rf $(WIKIMEDIA_ROOT)
