# This is all the operational stuff about the wiki. Dumps are
# retrieved from Makefile.dumps

###### WikiMedia vanilla build. ######
# Below is a wikimedia build that applies if you use a server stack
# that does not contain wikimedia.

HTDOCS_DIR=/opt/lampp/htdocs
HTDOCS_SUBDIR=wikipedia
WIKIMEDIA_ROOT=$(HTDOCS_DIR)/$(HTDOCS_SUBDIR)
WIKI_ROOTACCESS=fakeroot

## DOC
# This will try to set recursive perimission to htdocs directory with
# HTDOCS_PERMISSIONS which defaults to a+rw. Use symbolic or numerical.
HTDOCS_PERMISSIONS=a+rw

DIRECTORIES += $(WIKIMEDIA_ROOT)

## DOC
# Dependency: rsync
SYNC=rsync -zvr

.PHONY: htdocs-permissions
htdocs-permissions:
	$(ROOTACCESS) chmod -R $(HTDOCS_PERMISSIONS) $(HTDOCS_DIR)

wikimedia-tar-url=http://download.wikimedia.org/mediawiki/1.21/mediawiki-1.21.3.tar.gz
TAR_PROJECTS += wikimedia
wikimedia-build: wikimedia htdocs-permissions | $(WIKIMEDIA_ROOT)
	cd $(SOURCES_DIR)/wikimedia-archive/ ; \
	$(SYNC) $(SOURCES_DIR)/wikimedia-archive/*/ $(WIKIMEDIA_ROOT)

# Purposely avoided htdocs-permissions as a dependency. If we had
# created it we would be able to remove it.
wikimedia-uninstall:
	rm -rf $(WIKIMEDIA_ROOT)
