* Usage
  See the examples and work it out ;)

** Installing Bitnami MediaWiki
   Downloads and installs bitnami
   #+BEGIN_EXAMPLE
   make bmw-install
   #+END_EXAMPLE

   To have the downloaded stuff and the install dir in another path
   use
   #+BEGIN_EXAMPLE
   make bmw-install ROOT_DIR=/new/path/of/proj/root
   #+END_EXAMPLE

   NOTE: =ROOT_DIR= is not persistent. The default is the current dir
   and to run other commands based on an installed env keep redefining
   ROOT_DIR.

** Uninstalling Bitnami MediaWiki
   #+BEGIN_EXAMPLE
   make bmw-uninstall
   #+END_EXAMPLE

** Running Bitnami
   This will run apache and sql etc. To do any db operation be sure
   that it is running.
   #+BEGIN_EXAMPLE
   make bmw-run
   #+END_EXAMPLE

   This kills (a bit blindly) anything that resembles bitnami if it
   fails to halt gracefully.
   #+BEGIN_EXAMPLE
   make bmw-kill
   #+END_EXAMPLE

** Mysql
   To get some information about what will happen if you load stuff in
   the library run
   #+BEGIN_EXAMPLE
   make mysql-dump-info
   #+END_EXAMPLE

   To load stuff to the database (this will take care of installing
   anything missing so ideally you just need to run this)
   #+BEGIN_EXAMPLE
   make mysql-dump
   #+END_EXAMPLE
